defaults:
  - override hydra/job_logging: disabled

simulation:
  domain:
    lx: 4
    ly: 1
    nx: 400
    ny: 100

  solver:
    w: 1.72
    errormax: 1e-6
    itermax: 2000
    
  settings:
    ntsteps: 2000
    dt: 0.001
    mu: 0.01
    write_interval: 50

  boundary_conditions:
    bc: 2  # 1: Dirichlet, 2: Neumann

  vortex_variables:
    Vt: 1
    x0: 0.25
    y0: 0.5
    r0: 0.1